### ISSUE TITLE
[FEATURE] Add background color to Theme Repo and Plugin Repo

### ISSUE THREAD

**Issue by secp192k1** [maenDisease/Outlook#3]
```css
.contentRegion-3HkfJJ {
    background: var(--bg-overlay-chat, var(--gradient-kit-925a)), var(--background-primary);
}
```

Discord.: Slimakoi#6422
